### ISSUE TITLE
What is difference from otaboot.bin and otamain.bin?

### ISSUE THREAD

**Issue by toshibochan** [HomeACcessoryKid/LCMdev#6]
What is difference from otaboot.bin and otamain.bin?

**Comment by HomeACcessoryKid** [comment]
I advice you to go to the real repository. This repo is for hard-core developers.
There is plenty of info in https://github.com/HomeACcessoryKid/life-cycle-manager
If you have any questions after that, you can raise an issue there

**Comment by toshibochan** [comment]
I mean I can use otaboot.bin or otamain.bin will be the same?

**Comment by HomeACcessoryKid** [comment]
read the documentation I advised you to read and the answer is there. They are not the same else only one of then would have existed
